#!/usr/bin/env node
'use strict';
const { options } = require(process.env.HOME + '/.env');
console.dir(options);
const program = require('commander');
const axios = require('axios');
const user = options.GHUSER;
const token = options.GHTOKEN;
const ua = options.UA;
const { version } = require('./package.json');

function sendCreateRequest (opts) {
  const uri = 'https://api.github.com/user/repos';
  const thisForm = {
    name: opts.name,
    description: opts.description,
    private: opts.private
  };

  let rArgs = {
    url: uri,
    method: 'post',
    headers: {
      'User-Agent': ua
    },
    auth: {
      username: user,
      password: token
    },
    data: JSON.stringify(thisForm)
  };

  axios(rArgs).then(res => {
    const { clone_url } = res.data;
    console.log(`clone: ${clone_url}`);
    process.exit(0);
  }).catch(err => {
    console.error(err);
    process.exit(1);
  });

  //   function (err, res, json) {
  //   if (err) { return console.error(err); }
  //   if (!json) { return console.error(res.headers); }
  //   let cloneUrl = JSON.parse(json, null, 2).clone_url;
  //   return console.log(`clone: ${cloneUrl}`);
  // });
}

program.version(version)
  .description('add a new github repo')
  .option('-n, --name <str>', 'Repo Name')
  .option('-d, --description <str>', 'Repo Description')
  .option('-p, --private', 'Make this Repo private')
  .action(function (options) {
    sendCreateRequest(options);
  });

program.parse(process.argv);
