#!/usr/bin/env node
'use strict'
const options = require(process.env.HOME + '/.env')
const program = require('commander')
const request = require('request')
const user = options.GHUSER
const token = options.GHTOKEN
const ua = options.UA
console.log(options)
process.exit(1)
function sendCreateRequest (opts) {
  const uri = 'https://api.github.com/user/repos'
  const thisForm = {
    'name': opts.name,
    'description': opts.description
  }

  let rArgs = {
    url: uri,
    headers: {
      'User-Agent': ua
    },
    auth: {
      user: user,
      pass: token
    },
    form: JSON.stringify(thisForm)
  }

  request.post(rArgs, function (err, res, json) {
    if (err) { return console.error(err) }
    if (!json) { return console.error(res.headers) }
    console.log(JSON.parse(json, null, 2))
  })
}

program.version('0.0.2').command('add')
  .description('add a new github repo')
  .option('-n, --name <str>', 'Repo Name')
  .option('-d, --description <str>', 'Repo Description')
  .action(function (options) {
    sendCreateRequest(options)
  })

program.parse(process.argv)
